"""
cd_mcar.py — CD-MCAR: Content-Driven Multi-Criteria Adaptive Refinement
========================================================================
Core algorithm implementation for adaptive H3 DGGS grid generation.

The algorithm recursively refines H3 cells based on three criteria:
  - τ_n  (tau_n): minimum target count threshold per cell
  - τ_s  (tau_s): spatial concentration threshold (Gini-based)
  - τ_d  (tau_d): category diversity threshold

Reference:
  Zhang Aiguo et al., "Content-Driven Multi-Criteria Adaptive Refinement
  for H3 Discrete Global Grid System", IEEE J-STARS, 2026.

License: MIT
"""

from __future__ import annotations

import json
import math
from collections import defaultdict
from typing import Dict, List, Optional, Set, Tuple

import h3
import numpy as np
import pandas as pd

# ─────────────────────────────────────────────────────────────────────────────
# Default algorithm parameters (match Table 3 of the paper)
# ─────────────────────────────────────────────────────────────────────────────
DEFAULT_TAU_N = 5      # Minimum target count to trigger splitting
DEFAULT_TAU_S = 0.6    # Spatial-concentration threshold (Gini index)
DEFAULT_TAU_D = 3      # Minimum category diversity to trigger splitting
DEFAULT_MAX_RES = 10   # Maximum H3 resolution


# ─────────────────────────────────────────────────────────────────────────────
# Utility helpers
# ─────────────────────────────────────────────────────────────────────────────

def gini_index(counts: List[int]) -> float:
    """
    Compute Gini impurity index for a list of category counts.

    G = 1 - Σ(p_i²)   where p_i = count_i / total

    Returns 0.0 for a perfectly uniform or empty distribution.
    """
    total = sum(counts)
    if total == 0:
        return 0.0
    probabilities = [c / total for c in counts]
    return 1.0 - sum(p * p for p in probabilities)


def spatial_concentration(targets_in_cell: pd.DataFrame) -> float:
    """
    Compute spatial concentration (Gini-based density) for targets inside a cell.

    A higher value means targets are clustered rather than uniformly spread.
    The metric is defined over the spatial sub-quadrant distribution of centroids.

    Parameters
    ----------
    targets_in_cell : pd.DataFrame
        Must contain columns 'lon' and 'lat' (centroid coordinates).

    Returns
    -------
    float : concentration score in [0, 1]
    """
    if len(targets_in_cell) < 2:
        return 0.0

    lons = targets_in_cell["lon"].values
    lats = targets_in_cell["lat"].values

    lon_mid = (lons.max() + lons.min()) / 2
    lat_mid = (lats.max() + lats.min()) / 2

    # Assign each target to one of 4 quadrants
    quadrant_counts = [0, 0, 0, 0]
    for lon, lat in zip(lons, lats):
        q = (1 if lon >= lon_mid else 0) + (2 if lat >= lat_mid else 0)
        quadrant_counts[q] += 1

    return gini_index(quadrant_counts)


def category_diversity(targets_in_cell: pd.DataFrame,
                       category_col: str = "class_name") -> int:
    """Return the number of distinct target categories present in a cell."""
    if category_col not in targets_in_cell.columns:
        return 0
    return targets_in_cell[category_col].nunique()


# ─────────────────────────────────────────────────────────────────────────────
# Splitting decision
# ─────────────────────────────────────────────────────────────────────────────

def should_split(targets_in_cell: pd.DataFrame,
                 resolution: int,
                 tau_n: int = DEFAULT_TAU_N,
                 tau_s: float = DEFAULT_TAU_S,
                 tau_d: int = DEFAULT_TAU_D,
                 max_res: int = DEFAULT_MAX_RES) -> Tuple[bool, Dict]:
    """
    Determine whether a cell should be split further.

    A cell is split if ALL three criteria are met:
      1. |T_c| >= τ_n  (enough targets)
      2. ρ_s(c)  >= τ_s (targets are spatially concentrated)
      3. D_c     >= τ_d (sufficient category diversity)
    AND resolution < max_res.

    Returns
    -------
    (split: bool, metrics: dict)
    """
    n = len(targets_in_cell)
    s = spatial_concentration(targets_in_cell) if n >= 2 else 0.0
    d = category_diversity(targets_in_cell)

    criteria_met = (n >= tau_n) and (s >= tau_s) and (d >= tau_d)
    split = criteria_met and (resolution < max_res)

    return split, {"n": n, "s": round(s, 4), "d": d, "split": split}


# ─────────────────────────────────────────────────────────────────────────────
# Core recursive algorithm
# ─────────────────────────────────────────────────────────────────────────────

class CDMCARTree:
    """
    Adaptive H3 DGGS tree generated by the CD-MCAR algorithm.

    Usage
    -----
    >>> tree = CDMCARTree(tau_n=5, tau_s=0.6, tau_d=3, max_res=10)
    >>> tree.build(h0_cells, targets_df)
    >>> leaves = tree.get_leaves()
    """

    def __init__(self,
                 tau_n: int = DEFAULT_TAU_N,
                 tau_s: float = DEFAULT_TAU_S,
                 tau_d: int = DEFAULT_TAU_D,
                 max_res: int = DEFAULT_MAX_RES):
        self.tau_n = tau_n
        self.tau_s = tau_s
        self.tau_d = tau_d
        self.max_res = max_res

        self.nodes: Dict[str, dict] = {}   # h3_cell -> node info
        self.leaves: Set[str] = set()

    # ── public API ──────────────────────────────────────────────────────────

    def build(self,
              h0_cells: List[str],
              targets_df: pd.DataFrame,
              lat_col: str = "lat",
              lon_col: str = "lon",
              class_col: str = "class_name") -> None:
        """
        Build the adaptive tree from a list of H0 cells and a targets DataFrame.

        Parameters
        ----------
        h0_cells    : list of H3 cell indices at the base resolution (H0 layer)
        targets_df  : DataFrame with at minimum columns [lat_col, lon_col, class_col]
        """
        # Ensure coordinate columns exist
        if lat_col not in targets_df.columns or lon_col not in targets_df.columns:
            raise ValueError(
                f"targets_df must contain columns '{lat_col}' and '{lon_col}'."
            )

        # Rename for internal use
        df = targets_df.rename(columns={lat_col: "lat", lon_col: "lon",
                                         class_col: "class_name"})

        # Map each target to its H0 cell
        df = self._assign_to_h0(df, h0_cells)

        for h0 in h0_cells:
            res = h3.get_resolution(h0)
            targets_in_h0 = df[df["h0_cell"] == h0]
            self._recursive_split(h0, res, targets_in_h0, df)

    def get_leaves(self) -> List[dict]:
        """Return a list of leaf-node dicts, each with cell index and metadata."""
        return [self.nodes[c] for c in self.leaves if c in self.nodes]

    def to_json(self, path: Optional[str] = None) -> dict:
        """Serialise the tree to a dict (and optionally write to JSON file)."""
        data = {"nodes": self.nodes, "leaves": list(self.leaves)}
        if path:
            with open(path, "w") as f:
                json.dump(data, f, indent=2)
        return data

    def leaves_to_dataframe(self) -> pd.DataFrame:
        """Return leaf nodes as a tidy DataFrame."""
        rows = self.get_leaves()
        return pd.DataFrame(rows)

    # ── private helpers ──────────────────────────────────────────────────────

    def _assign_to_h0(self, df: pd.DataFrame,
                       h0_cells: List[str]) -> pd.DataFrame:
        """Assign each target to its H0 (base-resolution) cell."""
        res = h3.get_resolution(h0_cells[0])
        h0_set = set(h0_cells)

        def _map(row):
            try:
                cell = h3.latlng_to_cell(row["lat"], row["lon"], res)
                return cell if cell in h0_set else None
            except Exception:
                return None

        df = df.copy()
        df["h0_cell"] = df.apply(_map, axis=1)
        return df

    def _recursive_split(self,
                          h_cell: str,
                          resolution: int,
                          targets_in_cell: pd.DataFrame,
                          full_df: pd.DataFrame) -> None:
        """Recursively decide whether to split a cell."""
        split, metrics = should_split(
            targets_in_cell, resolution,
            self.tau_n, self.tau_s, self.tau_d, self.max_res
        )

        node = {
            "h3_cell": h_cell,
            "resolution": resolution,
            "n_targets": metrics["n"],
            "spatial_conc": metrics["s"],
            "diversity": metrics["d"],
            "split": split,
            "children": [],
        }
        self.nodes[h_cell] = node

        if not split:
            self.leaves.add(h_cell)
            return

        # Get children at next resolution
        children = list(h3.cell_to_children(h_cell, resolution + 1))
        node["children"] = children

        for child in children:
            # Assign targets to child cell
            child_targets = self._filter_to_cell(full_df, child, resolution + 1)
            self._recursive_split(child, resolution + 1, child_targets, full_df)

    @staticmethod
    def _filter_to_cell(df: pd.DataFrame,
                         h_cell: str,
                         resolution: int) -> pd.DataFrame:
        """Return only rows whose centroid falls within h_cell."""
        def _in_cell(row):
            try:
                return h3.latlng_to_cell(row["lat"], row["lon"], resolution) == h_cell
            except Exception:
                return False

        mask = df.apply(_in_cell, axis=1)
        return df[mask]


# ─────────────────────────────────────────────────────────────────────────────
# Convenience function
# ─────────────────────────────────────────────────────────────────────────────

def run_cdmcar(h0_cells: List[str],
               targets_df: pd.DataFrame,
               tau_n: int = DEFAULT_TAU_N,
               tau_s: float = DEFAULT_TAU_S,
               tau_d: int = DEFAULT_TAU_D,
               max_res: int = DEFAULT_MAX_RES,
               output_tree_path: Optional[str] = None,
               output_leaves_path: Optional[str] = None) -> CDMCARTree:
    """
    Run CD-MCAR and optionally save outputs.

    Parameters
    ----------
    h0_cells            : list of H3 base-resolution cell indices
    targets_df          : detection results DataFrame
    tau_n, tau_s, tau_d : algorithm thresholds
    max_res             : maximum H3 resolution
    output_tree_path    : if provided, write adaptive_tree.json here
    output_leaves_path  : if provided, write adaptive_tree_leaves.csv here

    Returns
    -------
    CDMCARTree instance
    """
    tree = CDMCARTree(tau_n=tau_n, tau_s=tau_s, tau_d=tau_d, max_res=max_res)
    tree.build(h0_cells, targets_df)

    if output_tree_path:
        tree.to_json(output_tree_path)
        print(f"[CD-MCAR] Tree saved to {output_tree_path}")

    if output_leaves_path:
        leaves_df = tree.leaves_to_dataframe()
        leaves_df.to_csv(output_leaves_path, index=False)
        print(f"[CD-MCAR] Leaves saved to {output_leaves_path}  "
              f"({len(leaves_df)} leaf cells)")

    return tree
